name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake g++

    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/build
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build

    - name: Test
      run: ctest -C Release
